# Generated by Django 6.1.1 on 2026-09-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('idade', models.PositiveIntegerField()),
                ('regiao', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, default='')),
                ('orcamento_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orcamento_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fumante', models.BooleanField(default=False)),
                ('aceita_pets', models.BooleanField(default=False)),
                ('tolerancia_bagunca', models.IntegerField(default=3)),
                ('nivel_organizacao', models.IntegerField(default=3)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
