# Generated by Django 6.1.1 on 2026-09-26 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nivel_organizacao',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tolerancia_bagunca',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
