# Generated by Django 6.1.1 on 2026-10-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0003_alter_perfil_nivel_organizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compatibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perfil_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades_como_a', to='perfis.perfil')),
                ('perfil_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades_como_b', to='perfis.perfil')),
            ],
            options={
                'unique_together': {('perfil_a', 'perfil_b')},
            },
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('curtir', 'Curtir'), ('recusar', 'Recusar')], max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('perfil_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_recebidas', to='perfis.perfil')),
                ('perfil_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_enviadas', to='perfis.perfil')),
            ],
            options={
                'unique_together': {('perfil_origem', 'perfil_destino')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('data_match', models.DateTimeField(auto_now_add=True)),
                ('perfil_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_a', to='perfis.perfil')),
                ('perfil_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_como_b', to='perfis.perfil')),
            ],
            options={
                'unique_together': {('perfil_a', 'perfil_b')},
            },
        ),
    ]
